version: '2'
services:
    sample2-app:
        image: sample2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sample2-mysql:3306/sample2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=sample2-elasticsearch:9300
        ports:
            - 9999:9999
    sample2-mysql:
        extends:
            file: mysql.yml
            service: sample2-mysql
    sample2-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: sample2-elasticsearch
